### ISSUE TITLE
Consider `PhysOcean.jl` for equation of state instead of MITgcmTools.jl

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/IsopycnalSurfaces.jl#10]
https://github.com/gher-ulg/PhysOcean.jl

**Comment by ggebbie** [comment]
Or
https://github.com/CliMA/SeawaterPolynomials.jl
https://github.com/TEOS-10/GibbsSeaWater.jl

**Comment by ggebbie** [comment]
Took JMZ (MIT gcm) equation of state and added to this package

**Comment by jrayshi** [comment]
EOS from https://github.com/gher-ulg/PhysOcean.jl is added in branch rayEOS.

**Comment by ggebbie** [comment]
Thank you @jrayshi! I'll take a look. We can try to turn this into a pull request and get it into the main branch. Once it's in the main branch, then I can use the TagBot to put this code in the official Julia version of the package.

**Comment by ggebbie** [comment]
2 equations of state now available: EOS80 and JMD95.  Next: add TEOS10 from GibbsSeaWater.jl.
