### ISSUE TITLE
issue about package loading

### ISSUE THREAD

**Issue by jrayshi** [ggebbie/IsopycnalSurfaces.jl#12]
When I tried to load the package, an issue occurred:

pkg> add ./IsopycnalSurfaces.jl
ERROR: refusing to add package `IsopycnalSurfaces [29a8b8bc]`: package `IsopycnalSurfaces = "29a8b8bc-eb2a-4ada-9a47-be49547c4d59"` already exists as a direct dependency

The error message is the same when I tried:
pkg> add IsopycnalSurfaces

**Comment by ggebbie** [comment]
The original SigmaShift package and the official IsopycnalSurfaces package have the same sha signature so they can't be loaded at the same time. Maybe this is the problem?

> From the package manager mode in the Julia REPL, try

rm SigmaShift

Then add IsopycnalSurfaces 

Feel free to send the output of
import Pkg; Pkg.status()
and I can troubleshoot better.

**Comment by jrayshi** [comment]
Hi @ggebbie,

The IsopycnalSurfaces package can be successfully loaded by using "add IsopycnalSurfaces" when I create a new environment in Julia REPL. 

However, there is an issue about the version compatibility when I tried to load IsopycnalSurfaces in my default env. Here is the error message after "add IsopycnalSurfaces": 
ERROR: Unsatisfiable requirements detected for package ClimateTools [4f4ee721]:
 ClimateTools [4f4ee721] log:
 ├─possible versions are: 0.9.0-0.23.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.9.0-0.23.1
 ├─restricted by compatibility requirements with ClimatePlots [b71d359b] to versions: [0.16.0-0.18.3, 0.20.0-0.22.0]
 │ └─ClimatePlots [b71d359b] log:
 │   ├─possible versions are: 0.1.0-0.4.2 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.4.2
 └─restricted by compatibility requirements with Interpolations [a98d9a8b] to versions: 0.23.1 or uninstalled — no versions left
   └─Interpolations [a98d9a8b] log:
     ├─possible versions are: 0.3.6-0.13.5 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions 0.3.6-0.13.5
     └─restricted by compatibility requirements with IsopycnalSurfaces [29a8b8bc] to versions: 0.13.0-0.13.5
       └─IsopycnalSurfaces [29a8b8bc] log:
         ├─possible versions are: 0.1.4-0.1.5 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions 0.1.4-0.1.5

It seems to conflict with the some packages I have already loaded. Do you have any idea to avoid this issue?

In addition, I copied the outputs of Pkg.status() of my default env.
julia> import Pkg; Pkg.status()
      Status `~/.julia/environments/v1.6/Project.toml`
 ClimatePlots v0.4.2
 ClimateTools v0.22.0
 Conda v1.5.2
 Dierckx v0.5.1
 GibbsSeaWater v0.1.1
 IJulia v1.23.2
 Interpolations v0.12.10
 MITgcmTools v0.1.5
 MeshArrays v0.2.25
 NetCDF v0.10.3
  PyCall v1.92.5
  PyPlot v2.10.0
  Revise v3.1.20

**Comment by ggebbie** [comment]
Appears to be a compatibility conflict with Interpolations.jl.  I believe that Interpolations.jl is not actually used in current version of IsopycnalSurfaces.jl.  If I remove this dependency, then hopefully the problem will be solved.
